services:
  core:
    container_name: MoFox-Bot
    image: ikun11451/mofox-core:latest  #master分支
    #image: ikun11451/mofox-core-dev:latest  #dev分支
    #image: ikun11451/mofox-core-classical:latest  #classical分支
    #build: .
    ports:
      - "8000:8000"    # 主程序
      - "12138:12138"  # WebUI
    environment:
      - TZ=Asia/Shanghai
    # 核心脚本：逻辑判断并启动
    entrypoint: ["sh", "-c", "if [ ! -d 'plugins/webui_backend' ]; then git clone -b webui-dist https://github.com/MoFox-Studio/MoFox-Core-Webui.git plugins/webui_backend; fi; exec uv run bot.py"]
    volumes:
      - ./.env:/app/.env
      - ./config:/app/config
      - ./data:/app/data
      - ./plugins:/app/plugins
      - ./data/core/logs:/app/logs
    restart: always
    networks:
      - mofox
  napcat:
    environment:
      - NAPCAT_UID=1000
      - NAPCAT_GID=1000
      - TZ=Asia/Shanghai
    ports:
      - "6099:6099"
    volumes:
      - ./docker-config/napcat:/app/napcat/config # 持久化napcat配置文件
      - ./data/qq:/app/.config/QQ # 持久化QQ本体
      - ./data/app:/app/data # 共享目录
    container_name: mofox-napcat
    restart: always
    image: mlikiowa/napcat-docker:latest
    networks:
      - mofox

  # chat2db占用相对较高但是功能强大
  # 内存占用约600m，内存充足推荐选此
  # chat2db:
  #   image: chat2db/chat2db:latest
  #   container_name: maim-bot-chat2db
  #   restart: always
  #   ports:
  #     - "10824:10824"
  #   volumes:
  #     - ./data/chat2db:/data/app
  #   networks:
  #     - mofox
volumes:
  site-packages:
networks:
  mofox:
    driver: bridge
